name: ExoticGarden
version: ${project.version}
authors: [mrCookieSlime, Goldentoenail, Joapple, SoSeDiK]
description: Дополнение к Slimefun, которое добавляет много новой растительности и еды
website: http://TheBusyBiscuit.github.io/
api-version: 1.13

main: me.mrCookieSlime.ExoticGarden.ExoticGarden

depend: [Slimefun]
softdepend: [CS-CoreLib]
